import { ContactMessage } from '@/src/domain/entities/ContactMessage';
import { IContactRepository } from '@/src/domain/repositories/IContactRepository';
import { prisma } from '@/src/infrastructure/prisma/prismaClient';

export class PrismaContactRepository implements IContactRepository {
    async create(data: Omit<ContactMessage, 'id' | 'createdAt'>): Promise<ContactMessage> {
        // contactMessage is correctly generated by Prisma from the ContactMessage model
        const contact = await prisma.contactMessage.create({
            data: {
                name: data.name,
                email: data.email,
                phone: data.phone,
                description: data.description,
            },
        });

        return new ContactMessage(
            contact.id,
            contact.name,
            contact.email,
            contact.description,
            contact.createdAt,
            contact.phone ?? undefined,
        );
    }
}
